install.packages("BiocManager")
BiocManager::install("dada2", version = "3.11")
BiocManager::install("DECIPHER")
BiocManager::install("phyloseq")
BiocManager::install("microbiome")
BiocManager::install("devtools")


install.packages("ggplot2")
install.packages("ape")
install.packages("optparse")
install.packages("nsprcomp")
install.packages("compositions")
install.packages("randomForest")
install.packages("pROC")
install.packages("PRROC")
install.packages("Hmisc")
install.packages("ggdendro")
install.packages("caret")
install.packages("MLmetrics")
install.packages("wesanderson")
install.packages("cowplot")
install.packages("ggpubr")
install.packages("ggrepel")
install.packages("testit")
install.packages("ini")
install.packages("showtext")
install.packages("svglite")